lifeops:
  services:
    user-service-url: ${USER_SERVICE_URL:http://localhost:8081}
spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: ${lifeops.services.user-service-url}
              predicates:
                - Path=/api/users/**


server:
  port: 8080
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG